// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pscqsexjlfwbvuoxkatl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzY3FzZXhqbGZ3YnZ1b3hrYXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDAzNTUsImV4cCI6MjA2NzkxNjM1NX0.nokcdEk3JMlQuMBbca26mEo2Sbb79xaOs2AFo695Q1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});